---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgCeOGD0NFnYguqxHAZsznjjDglS8O5XKiwRfw7b5ksC33/e+KYb3n+C4H3nyoYqf/tE9Ap0R+NLzufu65KZhmytTmzZloxr9QHhoqNrlHWR5dPJ4LRaLWjOXbT4Wy/9TGZxNJShTub4a863Uh5d5ran3uT/foqa0K6rX15EprEnYIFawVKO1uprpSZ7pXE05hKixBLPzBey5piASP7dOm36WYAtu3AgWoBzT8cXcA9DmSrB6Mp7wE/1mH+HmkAQh+AO0RsoCPO9zWU61HBh4mXGtqUWHIPSyaTJQA1ue96jlZnYH3dqyehsQ0DEGUVtSK68HVu26R/8L1y+ctPtSoye/3RXEFG+n/FW1XnB7OXgNQTBaG7nmnJA2b18kcr++RjoUMip81RWDnvgDgLW/MlDgWbJvfXR7Pg46QWnbIvLY0QG6J/ZdHS6v1fSCvPE75MymkosMJL9VHx+x8iWylSttDFcllh2E2d8EicwtgkADxlonlu/e8tVolYtx6si/KSZYxpQ5QI+xudi0UgliN5rUC/upWvxWxj9cNtS0VoAWJfxM1Ler22ZWSY9xLxb/3WTvqHM2ZUWNlmpHVqYCknJhtxu48VYVNtvA1iRHZ+kNhYT4Iey6NHXELCBLE9tL3ylE1u2mD4POL42OozLCl28BXz8Ri9YebIX9VkCXNT/0G+g/WCl6YRQdk9swri3P6LNsvL72aBKPm76jq5tIPUUtmX2tW1k1w6NOg+i0dPMCnqopJgHStqZBRqU+l6h/DI9TuOAxhW8ULwvxZ5KZ0v4DV+eKYF0S1YzUeA4hlI1R8+l4bnWJPB5RdXiERvNp4xDJ2pu0iHJTzfPgSi08G0xc2HhyY0tXmwAYvdwKt1wR5Rd3b6rN3XfwBVLAC07FFTJn7k+iUEfFV3TbhuskaM4Knm6M0CbRPoTTFAFE6ITCHerFw==
  template:
    metadata:
      name: ghcr-pull
      namespace: staging
    type: kubernetes.io/dockerconfigjson
