---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-introspection
  namespace: staging
spec:
  encryptedData:
    MCP_INTROSPECTION_SECRET: AgA1w3IFy40dL7SQeATVxTzufaTT6L1aIP0GV3F8CaUnvJUZMXQ0vlhxslAAZgGrmdKkeJLMjKVGZLO+wYXUTAr6eMzCy/Tsj3gdw7rj0JyFNhuOb7L0CA3V6gIUpCyrDldvwQsKgjLfYMP+8/xjZ0ygtFpPEilBZW1uhWc5H7ySe4cXmvVoCt8+7P9ihkmrDBV0w+MYz6bwfL+xO9nwGx9ZWVX9ETqCX6OIebU112OoBqIHt3A9TfNlaqdQJchktS2jWr/bXXoTFDAkLaLklTUf9AXBNshHCi3MKsOS/tDnpSQqYby11nmt5sMP35uksJ21iudU85WWNI1sJNjfmx1Bykn+AbDoEJ6FKe4o5IbbaXXrWywHaohwJrV4FTU2y+ZV+YYfR/7bZp2w3bRO37/fSV+h5oMxm8Zg0YU0bui9/sxZ02o+jaDRSkMr1++dvFeLrOQSdwHAbBqzZXk8RvVvmsc0Up7y4DSLgvWufaCH2frt3MwiNlPkXs4QkN12STZdD+pF0aoKMZ9t1LS5A9LCR5Rhe0qjYXw4vG+9QknoTkRQF8bfwTyFqds/N4xNGXNm9EfYY9of1whHTb6x+mJPlCUyPZs84Ey6dRCJ3hY+tNSDaePzLucxL9yFvB/IMHIQzim8SKCVx0QPUN88GPaA6NM167zT6TGhpfMT9FY9P72O9pWcJlODA47UDWTKmI3lelPlklfwF3LSFbfQVowaLz0VSxi7etPqwSoom7ILk43R2e13mWZok464gpgG5DG5dPDXrpfxAekEJJJ1xQDV
  template:
    metadata:
      name: mcp-introspection
      namespace: staging
