apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: report-download-signing
  namespace: staging
spec:
  encryptedData:
    REPORT_DOWNLOAD_SIGNING_SECRET: AgAPTVW3yJ/TXtKfDBDBqN+HPlBJ25XAg7MLvfZ/wxwsm5ZAXNCopOlT5QhW2UHRIVNDHk37sOQO5k71TTYtQ9q1b5X3Jx6lfztjRAna3rIqKrxt0n8QeZbOOvN/w9b7JioNgdPkX4xPf5t7+nRCzOyTUuhPkytNjTCtaGiXVXaSBW/myb/vq3S8O158ntN5WpEOGBUFOKwnE3KEJ7CYSkr1FH3Km34jjB64s+sHVm4mnt9C+HXZRohXWM3hECUBnZyuRD31L0Pg7l3NpTOaYvNyNbgt02sOwnP76WEVdHLWUB99b88UdIknL88gz1WZJTpqIGY/iiC0yI8CEQL2U/YEfsePT9lSCZFMaiNFHGG7C6XyQSHf/v6kciFU67ShApj8ja72eQJV2F30hICZOBhpCfZ4w8/eidRELik+hlkuBYiJfag0c+LqhnSWb3JIr0ZM98Cgl9H+FmwMTqzJAkrXoTIKuGITnNn3i123GfW7/Y9+GLFNPPkZa9n9asC2MsGjkj9GITV/qS61Xwh51YhiTkUJRosaqs4oflUncbr38XkRYcMcz3EAje6Kl5qg9efzzg9Er6vX8u3EGBwFYUs8MKZNIz2tcja2avJuJt5on3jNSNVyYnXdb17FQDtixrfTzOrBtP2DQ6NkHIkNxPuF5PgzObTFuSswjo1KTDvBNYwwB/lxqHH5suAcM12duOXsjGL0Yuw5Lz/tWO7+YdTtr2pIA8BtzF4+0pK3GRlXLJdy1M+kKtsA8V1+8DbWgq2osqdF4DgVLnmM+D3M95ybWw==
  template:
    metadata:
      name: report-download-signing
      namespace: staging
