---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-env
  namespace: staging
spec:
  encryptedData:
    REVENUECAT_WEB_API_KEY: AgAxFX7DMxvq3lui0SyOX2z/OOFcuKXtRI/ARt26Yh/tlo3OKo9edXgpe1Y5biFiBSYnpi7SdFa2N3o21WlUCrKuEhbt83X8ZslLtCDzUrduGxQLWuXDi02xMTy1ui1GAhBTw+hh7u8L7kLV9GZ4IQ1DDhrwBuxb8WhHrBkuYKNXYFbmMwDB0eX5u3NKA6ALR1CzT9IbiSd60nbAf7K089XCEyxk6nAMOB5gwTuF5vSoWGZ9s5MGt+XkD/qJxiAaGNCFvrkb0pOY68iYMlsh0nReKEeaXSIt11+D51VZEb4MHj5qP321v4yeCcInyBcb4o5gdHlNYxnv1V7jGHrI7hF25jyRGW0plfEE9rkgaAJZUabXgEIIxjraqelsMHpcilApgizQ2LEIpCoWEkp0+yRyErHr2iOGnNA/O6fVOdjDmvedPp9jgcuneOYnde80XA0nT+6fKGwyRTV/tomgS6kWyGCZx2wpb+RygTDFvXGD0wjIMBKH6G+KeXSpm0RLIpqfRwztPej7J/ZvAMcu9/RLei319XLsbFer6byzswnMUEioXnnRi/+jZJ4iR6y7JWS6FkiinbakzkKSXnXhWz7quJkbYzTeTT1F07qh+I4FI+W8Sm60dhgwjkcI6uxLOEM3euz2WO50qj6raFroxD8UcVIG34EM0BPrPCP36pQp9Yerw3TpqBZYiWt4k2uPbK5HjgQ1TV/gqyqdptX+C2C/C/+DWQYycoYopp4PtJSgHg==
    SESSION_SECRET: AgCu0Caw6Clrcpdgb9HwbedetbyrIdu2NxDTX9ESAtRsO5kxgpYe2Wp+Ln6eWidhJ1e2W+V8+Gv2hy9i0li6kkMq3JbOjweEMNi6i6L2RKWueAVmzsaWoLO191f2iqL//QJgGImBnbC4wHYR6JhHaB51kT+OpAoLNVpT48clWYq2lowBjRvGY1jZ3pqNRbyPaolCerVR2cp6H0Jx/oAqAQuYccV8FpUjZBXZEjXLWerajgR805nuyT/9PbWVmqLWXuqzvHpBz5qeZ3v8+1bo0Iqvbj8Mgysn/m41VE2lTuDnsR7aNcJixKkhrFKlS2sUxtvOKoUvr9amClJBgRDOmvlryiAHL/hxHQH6jECUSDO8WNum7AtQ0Kp0HQ7ojpMWfdH1YTV9T6UzmCaiF1mg+kNd/TX7EdS5BXKk1UUaM8AZi5hYDEyiZM+SlFtfB8KlOXTdvF0ygmKb16WC1xXkHMGNulmV20aaNbSm0b6ZlL5ksctVugQZtrJfyIRaOyXPDyghVzIFSZf3WjRuNKwpuG8sLuKwwzkSXKhSYSoLQE3CXA1EcAkgo20Zx5PPNhp74qmArDFwmjCSqNpuKbFLeK55cFGv6FyfolzgolSAB11qjSmTqkWIdWKJIMPFnvDjVVyUc3oxSQLVGmTDgHgypvr81skRdXfVbLfFVHLnz2a3qdyMp6B+Cb+k8We6QzTN7LK4uumz8cEZG9FIVPYE/GEDLhE27n1TJSKm5pkCGX/P14VU8tl8WszOrUUqg99RWVcGRgUbm1K5uWV7qdSIXPux
  template:
    metadata:
      name: web-env
      namespace: staging
