---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-staging-htpasswd
  namespace: staging
spec:
  encryptedData:
    users: AgAWTH3k9UEp31YhziYnfk1H2wlbHls7SpVmVBRrB9OK7yot67Dx1IoPOl66wPJLD/gzqtrPGB+VwCvmpR5vnIH+442DMuacargAhBeej9Z2JmcGZ6rKxN+ACsyiZhZ6q9areh7jLz5zHMIbYS4Vl/XDhW2Al9TZAcSZejT8wP5elbjE01Pnl6S5dbneqrvgh+hygrmFzi6+H+MkJa8AOxuI3xZOscl6ojUeibho0nilj5PAe4AX33MBC5xwRT1CtTRvFBBPfNS0by7FIN1jfOULGrAuLuBazw3BYQjZn9+5KKF9BDclyhomu8rQVUgHrhk9kJwuXZI0vYvFkEz6eB85MYiB00Xct0d/UNxE5BPmdbH/Swtoee4BTMYtGLcCM3odIv6eapcO8yz7AZ08cDbfAK/iUyN1VMVCPYLh0yRDBOet4S9BCec6QfdUfs9bkIGoPUSieqAaPI6dHriELGDsLhyvM8BaarMKWJ136uYg1rV/PiRs5EZWURJkNpsudEKauD5h4IL5+ALHMzPWBWMDDmbBeQN4e5HmRw+VA3Jfzhi1kkbqpp+q6fzmkJeEImFUicC9NYzV1XqU2WLU7Vxw94MV1YNbLJJ9m/IM3XZiaWAVn65nU03m8ksxDyiajt4L9Klc9l6dkd94HDuPTri9uYEQ4/1CrWhL6euka7ljTzjbZ8tpbXuvSulUPZ+duRfy7lsn8TmMtmcdY0G3cx60Qbikb9BDUfpdRH9cOF9Lx2mVnw8DXCB19CV8JRLoL5n+88ysAwo4v5F8NACU7t/+1wFm
  template:
    metadata:
      name: web-staging-htpasswd
      namespace: staging
