---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: production
spec:
  encryptedData:
    .dockerconfigjson: AgAn7p/1YMIUWox728TUEzo9B1sthgx10zszp3uguqgNShx0QFCZi8eqgaUq+ZU/7F4MK+eQl2j5PAqQhakfHZy5x4x1wvwuQ/SQNK5LGB4XqFGJs2Fi1tcR33dagkgeUufM/P0d1xOc62dsLHiVPHH/wrO4YoMJ+hXvezux8rUx3YqC6PnsAeHnZtC5ABDhToZt8XIL591/hNDip0al8SdPAUV6ORHUY2EvHQfu5dgFeBuIszd9l+bZbIG7IJJWGEb6mZqpnUXhcdlq84jYraMCGqTufHUeORCx998gdDx0xzoa2a5euzLkJ4F3BaAP/S8QEJgHYXkuRKkVZmMuM4tVVWTnJU7JjBSN3Izhr02t3JWYrKvanuCWwmB5JA51WsV3yS3Q7UqCWOvy5x75CAoh3R8zKkNHshkeSTnvL6q0+Pcv4prRwGdJf5nKYN8Jboj3gpK2fn9wkF21IFQq2Ti2RlRc2NQuD/UIYzPmZrvS4qxdslsLEdLdqjAqan2wvMAgZ5HWQPU7zxKR/+6r0RxLXS1j+aJpBJEgpTnt71F3IfPgIJJ9gnwETa9ayAwP2U52evRVUda3g9qdtbQ/vsSdFmDpq79EWub+j39mM7pLgsbjQS+qXv46lxkuOdXFYM5WO4Z4gn4BxnOQvnCCsLbF+2VJM1Ab3AN2bwsMBdbaUzr+VnyJeFe7Q3B9Kdkk/qhO9QLb7pMGh/LGNYoOA5UOhbokQI4hkL7koD0g0cQIlImKj8MoRoLmrjM/9Z+gxGW/qnolFsdJ8Gt0pKqEomkpWp8ECwVon7s+Jdse5RksYVe4DfE/yNMQ+LBTBWgmPWgUTDbexBmOBotN09mG+hY8n8ra0Y6f6N8O0GZDgm80AUm0Y+LmMt+JojGiPtU/y3YaoGwBekctIF8V5HSxi2nS+jpUGcFwrICBVmM1VWx2qoUmjA==
  template:
    metadata:
      name: ghcr-pull
      namespace: production
    type: kubernetes.io/dockerconfigjson
