---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-introspection
  namespace: production
spec:
  encryptedData:
    MCP_INTROSPECTION_SECRET: AgCgC3wgemar1XlaPZ77iqoZaqml+UmGztTKgHSwUFJW8xsCtpo7kBIn8Nf7QbbU32OE/eMKBjULyHlGvBI1m8semg+CPekh682XtKa2bZwH4EZTi0j5dVtUMmomULY0JQOyU3CDMIl1K1sniEOb8cBoTwwnRCslShX7fuML9NTA+AI0ZkZl189IGjXbzhfIhfoPiGBmCNfMLF7xyNsaUjM8hn03agAr7Qr3ZOxu4owvIq7WHxSP81EB0FcjvNVDQkFuxC3xxnXsGhEpUGqOzi/HQcheDv3RaydfUPy9V7qFmrhLVYPPCT4kJRYiqRuOUvQF0adqLikHKq6DFoNpn/j20RrjThypswhVKhMmgD3MsXYHeQkbjN0WtoXua993QMm7wRgv7NsRAdyvjqGVS0H3eghi2NPuBXgKF3Cq2rYUAF63jlEX+efCP4ezg0QEbn2Q/moX3ZAheJzk0zEviGcvzv0+VJ1Dvt7x7O+cZkxVoGVH3eg4pkgofrGLILx2WjuXLuddztkfzLe2gaAhXf2kiiux7eY6AMVjsk3E87lvU7GD1E1Q2pzq71mk7gYxEKl4GqZBp2TjH9QD4uNLmKvJGnPP8sfwYgA1pSaAEITEJjWhQGn+Gmc7bVXFpQrzLlJEPSWxJl5qHXPckrWeoootkylJjwNj+igg3j/068MZhwsvdJoZGpfuekzdcZr02NQyiolEeGkJfKwlx5vMqXLxUMwojIgK4jF6GeKXSKcWKzDf5OZCZVab3ju4Ww+DBktqAJbZe5ywEZLFrr/PP/sI
  template:
    metadata:
      name: mcp-introspection
      namespace: production
