apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: report-download-signing
  namespace: production
spec:
  encryptedData:
    REPORT_DOWNLOAD_SIGNING_SECRET: AgBFaRqODrKIQhq4i//JHXTifegbHHzO8PLoseYef+53nAaztJS3yV/YSr5QAj+8OsSzhvPJnsWLIUye0riXtUblTuGlAvvOUkdxkDnC2eqXmYDU2APfqTFCQdVS9NO0uzzXjzXhx0QqbsLXTGUuxb8sgTaYnxgiPkqjTPZ9Uzb+kYjL12vNsE5TFmrdp7Ia7KCZdaT1WhYr9L2ddV8x5j2X78nViEg08S81MxcdDRrb49ctiaxGm7UuJ5BTEEGYopr4zgS9gyzNROe0XbGz5FtRjRuxK+7imAChOaFe3fSIimIWjylf2socY7ybocjWsWKNT2760r7P+y0/m2UXm40eqIev96av1RenCJ++/QgZayBsBU4TzWGoeAv/gS4vdNipMlzmLozS7SF4vwRKnnSKWS3VB9lxi0b23NHkUjWGlVGAGj2LC6WhXYYbi2/7324AWGD/NMfh6i6oWtd/sHUEroADw7g+WbDgUX91RD+rhwtwMpjk9ic1Ag88LRnA2kEuF8FsvEmhQQgf290ya5A+yjzR3xiVps47Y2zyx2lTdFaOf24UjAA1wRMgEH7VkGY51LdKIoJioSaIOLvfQs7q3ywGXs/4v/G8Nf/BSyR6sVgiRD0fg/kxdtELViios1LarzYstPBwSICvwBra5XV0i6o9O4h5NUsKK/SI6p4W8qNjgTZIRKimL0WGATHQlY5O1AV+34DCWbLOjgyivwwn6UvnhqR5GaqXs0z275OEOp58fjLqWwUl9NGhgMUPeFyXg14raN3uAvNRH6SsthOwlg==
  template:
    metadata:
      name: report-download-signing
      namespace: production
