---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-env
  namespace: production
spec:
  encryptedData:
    REVENUECAT_WEB_API_KEY: AgAVzTF1OSrYX/LCYh089CR4Gp+kAtK6K9DCOLFNKHy4VFHVYqvVsBKb/I8zA3epy5qQ8lXOt6jBtmHeSxh0ieJMB/IYc0QIXDOKv2MB4geM8/F1YOZVykf5GIOnKPpuofPYk3rkjPsT2xZYQ/eNxRhxZbEmmGyj5ZGgdqP8SQ0Ra9NI3KiAX9ylN7vYcRGE26l6LCj/z7k43MlIyIgK6cxVh/I9HWTzj6UNpa13qALNcWk41qu8zJtYX7ZzlhZdrtvVziciTmvYqCsKypyVWoOD4dwJ8OHt732vwCM365ZqLhXHbTCvlzjE4iYAYBdE5mlOhOSETfF69w96kdw4mSFRXZl9e88FbQsWfW/VWSrKk7GcROyaFYOQBKuMm/obTw7v2k/TCzencbSPm9aBnJ9VyutbE6EEgAG1+kMm20hmd3Sg61i4PDcQP0m+bzpuNJ4a1YAPnIzxbqvILXV6kfJmf/LeIL2rpKjeZfvbd96tj843yC+tWLqKj4ELjOTHwS2dWQ/jqDRsrujdlYDixRX5UtUAVh7mP7rww93vzfTMVo/PPk6b7dxNfscSh3YVP7OAD8gd0XbH7x6l1mbGWcVayLO5kpIuYXb9xSkJpPXByAQDgRqT0w4KPqJz9HyRPYWhSduFGzemD9b4OtId0d+Cd0OnYsEwF2t3sdyDdL4UJ43tAGfV0tJLozxfVXGqVhZSyx4i1LQWQHHS7J6HNOw9tjpz0zY0E8OdHoohbE5t6g==
    SESSION_SECRET: AgBFKnqZMY24XDL4Gt9o2Ti7qXvqxwGFgh8IC9jUM3JGWd0bEfSDOtcoGSOG85vrHklwql0tLlBAL0IdCAuS2T1GmlLH7NEr3+WxwEYOFRQcCjkP3Rq2T6aWI/ylXQzisCl/kTVH1IqxFdO+eVtKr0DTCDE+6YF4r848qQe8pnL1DIa8w13ntokMk27OM4iwyWJuUf87FQexl0esD39HgFZyTcxyqhM/I/B3VxrGGf41TmDhMvYbkoKgbbnz+nfPTe+SrXz0LOESdCVwf8B5aHQ5U3U5lLti+a+7PKQBFnsqmb773xq38lv/EB+y6lFEyHccNEZ+YKlwabzZZMtg/jP3kreqcYRTd4u5Taa8pnhfMRppuKlr+1xPtajthidBkJEHEfx0B6FDzLA4ikQ6uWlA00DbJMBeVBoLc8pLieiHqe4lveiMI7oFkxqyq1078PzKkOCXCRrYSRxX2LQj8zG9nH3ZGxqKln8xhnHhvKHpwJlUy+N7xG1JxGYjzAsa15+mkUZLv+qVn85aUwvcjZBy2WwFJi0/DOhSHvve+ZSXAYY7Rbz7dax1XNqtRHFhy9wUOw1T5npw980/VAW2eVHZz61L357V3TFnZD/pvWC3Sr4eatyMsn/da8HcyO9jNuzh3Lzs83lrCE7DNY/zJT3aT3jVkO7xmnhR81tVn4Vst1dUUIPB4jozPqC4yVGitLOlfP5/oxdu2jBqOs3UrJv8Jc+/C+zepbhtjxm4/hmpQltq++XQlcgqleORFmTXkAkCQ11pNuswiar4Ym26quId
  template:
    metadata:
      name: web-env
      namespace: production
